MK_THIS=        ./mk/
MK_COMMON_DIR=  ./../mk/

include $(MK_COMMON_DIR)defs.mk $(MK_THIS)local_defs.mk

SRC=    $(addprefix $(SRC_DIR), \
	Core.cpp 		\
	CoreGui.cpp 		\
	ProcessManager.cpp 	\
	Timer.cpp 		\
	main_plazza.cpp		\
	main_plazza_gui.cpp	\
	)

include $(MK_COMMON_DIR)rules.mk
