MK_THIS=        ./mk/
MK_COMMON_DIR=  ./../mk/

include $(MK_COMMON_DIR)defs.mk $(MK_THIS)local_defs.mk

SRC=    $(addprefix $(SRC_DIR), \
	FileReader.cpp		\
	FileScrapper.cpp	\
	RegexParser.cpp		\
	)

include $(MK_COMMON_DIR)rules.mk
